cloudcannon:
  data: true

sass:
  sass_dir: _sass

collections:
  posts:
    output: true
    permalink: /:year/:title
  portfolios:
    output: true
    permalink: /:categories/:title

uploads_dir: assets/images

plugins:
  - jekyll-webp
  - jekyll-sitemap
  - jekyll-archives

webp:
  enable: true

icons:
  - "Facebook"
  - "Twitter"
  - "Github"
  - "Instagram"
  - "Stack Overflow"
  - "LinkedIn"

categories:
  - website
  - pwa
  - web-app
  - e-commerce
  - jekyll
  - rails
  - javascript
  - gsap
  - webflow
