general_settings:
  site_title: Frontend Web Development
  site_url: 'https://itsgus.dev'
  preview_image: /assets/images/cover.jpg
  social:
    - icon: "LinkedIn"
      url: 'https://linkedin.com/in/gus-schiavon'
    - icon: "Github"
      url: 'https://github.com/guschiavon'
theme:
  heading_font_family: '"Glegoo", serif;'
  body_font_family: '"Bitter", serif;'
  dark_color: '#222'
  light_color: '#d2d2d2'
  accent_color: '#1fc71f'
seo:
  description_text:
  fb_app_id:
  keywords: []
configuration:
  head_code_block: '
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,200;0,300;0,400;0,700;1,200;1,300;1,400&family=Glegoo:wght@400;700&display=swap" rel="stylesheet">'
  body_code_block: